apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
spec:
  type: NodePort
  ports:
  - port: 8200
    targetPort: 8200
    nodePort: 30820
    protocol: TCP
    name: vault-port
  - port: 8201
    targetPort: 8201
    protocol: TCP
    name: cluster-port
  selector:
    app: vault
